name: RxSwift Specs

on:
  push:
    branches:
      - main

jobs:
  specs:
    name: "CocoaPods Spec Test"
    runs-on: macOS-latest

    strategy:
      matrix:
        target: [RxSwift, RxCocoa, RxRelay, RxBlocking, RxTest]

    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode 12
        run: sudo xcode-select -s /Applications/Xcode_12.4.app
      - name: Test Specs
        run: CI=1 TARGET=${{ matrix.target }} SWIFT_VERSION=5.1 ./scripts/validate-podspec.sh